server {
  listen 5173;
  server_name _;
  server_tokens off;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  client_body_temp_path /tmp/nginx/client_temp;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
