CREATE INDEX "article_asset_article_usage_sort_idx" ON "article_asset" USING btree ("article_id","usage_type","sort_order");--> statement-breakpoint
CREATE INDEX "article_asset_asset_idx" ON "article_asset" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "article_board_status_posted_idx" ON "article" USING btree ("board_id","status","posted_at");--> statement-breakpoint
CREATE INDEX "article_status_posted_idx" ON "article" USING btree ("status","posted_at");--> statement-breakpoint
CREATE INDEX "article_author_status_posted_idx" ON "article" USING btree ("author_user_id","status","posted_at");--> statement-breakpoint
CREATE INDEX "asset_created_idx" ON "asset" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "asset_uploaded_by_idx" ON "asset" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX "audit_log_actor_created_idx" ON "audit_log" USING btree ("actor_user_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_log_target_created_idx" ON "audit_log" USING btree ("target_type","target_id","created_at");--> statement-breakpoint
CREATE INDEX "bulk_email_sent_idx" ON "bulk_email" USING btree ("sent_at");--> statement-breakpoint
CREATE INDEX "bulk_email_sender_sent_idx" ON "bulk_email" USING btree ("sender_id","sent_at");--> statement-breakpoint
CREATE INDEX "comment_article_status_created_idx" ON "comment" USING btree ("article_id","status","created_at");--> statement-breakpoint
CREATE INDEX "comment_author_status_created_idx" ON "comment" USING btree ("author_user_id","status","created_at");--> statement-breakpoint
CREATE INDEX "executive_contact_sort_idx" ON "executive_contact" USING btree ("sort_order");--> statement-breakpoint
CREATE INDEX "student_fee_status_status_updated_idx" ON "student_fee_status" USING btree ("status","updated_at");--> statement-breakpoint
CREATE INDEX "survey_answers_response_idx" ON "survey_answers" USING btree ("response_id");--> statement-breakpoint
CREATE INDEX "survey_answers_question_idx" ON "survey_answers" USING btree ("question_id");--> statement-breakpoint
CREATE INDEX "survey_questions_section_sort_idx" ON "survey_questions" USING btree ("section_id","sort_order");--> statement-breakpoint
CREATE INDEX "survey_responses_survey_status_submitted_idx" ON "survey_responses" USING btree ("survey_id","status","submitted_at");--> statement-breakpoint
CREATE INDEX "survey_responses_survey_user_idx" ON "survey_responses" USING btree ("survey_id","user_id");--> statement-breakpoint
CREATE INDEX "survey_responses_user_created_idx" ON "survey_responses" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "survey_sections_survey_sort_idx" ON "survey_sections" USING btree ("survey_id","sort_order");--> statement-breakpoint
CREATE INDEX "survey_connected_article_published_idx" ON "survey" USING btree ("connected_article_id","is_published");--> statement-breakpoint
CREATE INDEX "survey_published_created_idx" ON "survey" USING btree ("is_published","created_at");--> statement-breakpoint
CREATE INDEX "survey_creator_idx" ON "survey" USING btree ("creator_id");--> statement-breakpoint
CREATE INDEX "user_role_group_user_active_idx" ON "user_role_group" USING btree ("user_id","is_active");--> statement-breakpoint
CREATE INDEX "user_role_group_role_active_idx" ON "user_role_group" USING btree ("role_group_id","is_active");--> statement-breakpoint
CREATE INDEX "users_active_name_idx" ON "users" USING btree ("is_active","name_ko");
