const assert = require("node:assert/strict");
const test = require("node:test");
const XLSX = require("xlsx");

const {
  parseRoadmapWorkbook,
} = require("../dist/apps/api/src/features/roadmap/roadmap-importer.js");

function buildWorkbook() {
  const sheet = XLSX.utils.aoa_to_sheet([
    [
      "개설년도",
      "개설학기",
      "개설학과",
      "과정구분",
      "과목구분",
      "교과목코드",
      "교과목명",
      "분반",
      "과거 과목번호",
      "강 : 실 : 학",
      "담당교수",
      "영어",
      "정원",
      "수강인원",
      "강의시간",
      "강의실",
      "강의유형",
      "원본 추가 컬럼",
    ],
    [
      2026,
      "봄학기",
      "전산학부",
      "학사과정",
      "전공필수",
      "CS.20300",
      "시스템 프로그래밍",
      "A",
      "CS230",
      "3.0 : 0.0 : 3.0",
      "담당 교수",
      "Y",
      40,
      20,
      "월 10:30~12:00",
      "E3-1",
      "대면",
      "그대로 보존",
    ],
    [
      2026,
      "봄학기",
      "전산학부",
      "학사과정",
      "개별연구",
      "CS.49999",
      "개별연구",
      "",
      "",
      "0 : 0 : 1",
      "",
      "N",
      "",
      "",
      "",
      "",
      "대면",
      "제외 대상",
    ],
    [
      2026,
      "봄학기",
      "경영대학",
      "학사과정",
      "전공선택",
      "BA.10000",
      "경영 과목",
      "",
      "",
      "3 : 0 : 3",
      "",
      "N",
      "",
      "",
      "",
      "",
      "대면",
      "제외 대상",
    ],
    [
      2026,
      "봄학기",
      "전산학부",
      "대학원",
      "전공선택",
      "CS.60000",
      "대학원 과목",
      "",
      "",
      "3 : 0 : 3",
      "",
      "N",
      "",
      "",
      "",
      "",
      "대면",
      "제외 대상",
    ],
  ]);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, "2026 봄");
  return XLSX.write(workbook, { bookType: "xlsx", type: "buffer" });
}

test("roadmap import keeps eligible rows and preserves raw columns", () => {
  const result = parseRoadmapWorkbook(buildWorkbook(), "fixture.xlsx");

  assert.equal(result.rows.length, 1);
  assert.equal(result.skippedCount, 3);
  assert.deepEqual(result.rows[0], {
    capacity: 40,
    courseCode: "CS20300",
    legacyCourseCode: "CS230",
    credits: "3:0:3",
    currentCode: "CS.20300",
    delivery: "대면",
    enrolled: 20,
    inEnglish: true,
    instructor: "담당 교수",
    nameKo: "시스템 프로그래밍",
    room: "E3-1",
    section: "A",
    sourceData: {
      "개설년도": 2026,
      "개설학기": "봄학기",
      "개설학과": "전산학부",
      "과정구분": "학사과정",
      "과목구분": "전공필수",
      "교과목코드": "CS.20300",
      "교과목명": "시스템 프로그래밍",
      "분반": "A",
      "과거 과목번호": "CS230",
      "강 : 실 : 학": "3.0 : 0.0 : 3.0",
      "담당교수": "담당 교수",
      "영어": "Y",
      "정원": 40,
      "수강인원": 20,
      "강의시간": "월 10:30~12:00",
      "강의실": "E3-1",
      "강의유형": "대면",
      "원본 추가 컬럼": "그대로 보존",
      __sourceFile: "fixture.xlsx",
      __sourceRow: 2,
      __sourceSheet: "2026 봄",
    },
    term: "2026-spring",
    time: "월 10:30~12:00",
  });
});
