import { FormEvent, useEffect, useState } from 'react';
import type { EventItem, EventVisibility } from '@soc/contracts';
import { adminEventApi } from '@/lib/admin-event-api';
const initial = { titleKr: '', titleEn: '', descriptionKr: '', descriptionEn: '', start: '', end: '', location: '', visibility: 'PUBLIC' as EventVisibility };
export function AdminEventsPage() {
  const [items, setItems] = useState<EventItem[]>([]); const [form, setForm] = useState(initial); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { try { setItems((await adminEventApi.list()).items); } catch { setMessage('행사 정보를 불러오지 못했습니다.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setMessage(''); try { await adminEventApi.create({ titleKr: form.titleKr, titleEn: form.titleEn, descriptionKr: form.descriptionKr, descriptionEn: form.descriptionEn, startAtMs: new Date(form.start).getTime(), endAtMs: new Date(form.end).getTime(), allDay: false, location: form.location, visibility: form.visibility }); setForm(initial); await load(); setMessage('행사를 추가했습니다.'); } catch { setMessage('행사를 추가하지 못했습니다.'); } };
  return <section><h1 className="border-b pb-4 text-[32px] font-extrabold">행사 관리</h1>{message ? <p role="status" className="mt-4">{message}</p> : null}
  <form onSubmit={submit} className="mt-6 grid gap-3 rounded-lg border bg-white p-5 md:grid-cols-2">{(['titleKr','titleEn','descriptionKr','descriptionEn','location'] as const).map((key) => <input key={key} required aria-label={({titleKr:'제목 (한국어)',titleEn:'Title (English)',descriptionKr:'설명 (한국어)',descriptionEn:'Description (English)',location:'장소'})[key]} value={form[key]} onChange={(e) => setForm({...form,[key]:e.target.value})} className="rounded border px-3 py-2" />)}<label>시작<input required type="datetime-local" value={form.start} onChange={(e) => setForm({...form,start:e.target.value})} className="ml-2 rounded border px-3 py-2" /></label><label>종료<input required type="datetime-local" value={form.end} onChange={(e) => setForm({...form,end:e.target.value})} className="ml-2 rounded border px-3 py-2" /></label><select aria-label="공개 범위" value={form.visibility} onChange={(e) => setForm({...form,visibility:e.target.value as EventVisibility})} className="rounded border px-3 py-2"><option value="PUBLIC">전체 공개</option><option value="AUTHENTICATED">로그인 사용자</option><option value="COMMITTEE">집행위원</option></select><button className="rounded bg-kaist-darkgreen px-4 py-2 font-bold text-white">행사 추가</button></form>
  {loading ? <p role="status" className="mt-6">불러오는 중...</p> : <ul className="mt-6 divide-y rounded-lg border bg-white">{items.map((item) => <li key={item.id} className="flex items-center justify-between gap-4 p-4"><div><strong>{item.title.value}</strong><p className="text-sm text-kaist-grey">{new Date(item.startAtMs).toLocaleString('ko-KR')} · {item.location}</p></div><button onClick={() => void adminEventApi.delete(item.id).then(load).catch(() => setMessage('행사를 삭제하지 못했습니다.'))} className="rounded border border-red-500 px-3 py-1 text-red-600">삭제</button></li>)}</ul>}
  </section>;
}
