import { useEffect, useState } from 'react';
import type { AdminVote, CreateVoteRequest } from '@soc/contracts';

import { GovernanceApiError, voteApi } from '@/lib/governance-api';

const localDateTime = (date: Date) => { const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); };
const toIso = (value: string) => new Date(value).toISOString();

export function AdminVotesPage() {
  const [items, setItems] = useState<AdminVote[]>([]);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ titleKr: '', titleEn: '', descriptionKr: '', descriptionEn: '', opensAt: localDateTime(new Date(Date.now() + 60 * 60 * 1000)), closesAt: localDateTime(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)), validTurnoutPercent: '50', candidate1: '', candidate2: '' });
  const refresh = async () => { try { setItems((await voteApi.adminList()).items); } catch { setError('투표 목록을 불러오지 못했습니다.'); } };
  useEffect(() => { void refresh(); }, []);
  const create = async () => {
    if (!form.titleKr.trim() || !form.titleEn.trim() || !form.candidate1.trim() || !form.candidate2.trim()) return;
    setSaving(true); setError('');
    const input: CreateVoteRequest = { titleKr: form.titleKr.trim(), titleEn: form.titleEn.trim(), descriptionKr: form.descriptionKr.trim() || form.titleKr.trim(), descriptionEn: form.descriptionEn.trim() || form.titleEn.trim(), opensAt: toIso(form.opensAt), closesAt: toIso(form.closesAt), anonymous: true, validTurnoutPercent: Number(form.validTurnoutPercent), candidates: [{ nameKr: form.candidate1.trim(), nameEn: form.candidate1.trim() }, { nameKr: form.candidate2.trim(), nameEn: form.candidate2.trim() }] };
    try { const created = await voteApi.create(input); setItems((current) => [created, ...current]); setForm((current) => ({ ...current, titleKr: '', titleEn: '', descriptionKr: '', descriptionEn: '', candidate1: '', candidate2: '' })); } catch (cause: unknown) { setError(cause instanceof GovernanceApiError ? cause.code ?? '생성에 실패했습니다.' : '생성에 실패했습니다.'); } finally { setSaving(false); }
  };
  const transition = async (item: AdminVote, action: 'open' | 'close' | 'publish') => { setError(''); try { const updated = await voteApi.transition(item.id, action); setItems((current) => current.map((row) => row.id === updated.id ? updated : row)); } catch (cause: unknown) { setError(cause instanceof GovernanceApiError ? cause.code ?? '상태 변경에 실패했습니다.' : '상태 변경에 실패했습니다.'); } };
  const importCsv = async (item: AdminVote, file: File) => { const entries = file.name.toLowerCase().endsWith('.tsv') ? (await file.text()).split(/\r?\n/).filter(Boolean).map((line) => line.split('\t')) : (await file.text()).split(/\r?\n/).filter(Boolean).map((line) => line.split(',')); const parsed = entries.filter((row) => row[0] && row[1] && row[0].toLowerCase() !== 'kind').map((row) => ({ identityKind: row[0].toUpperCase() === 'SSO_SUBJECT' ? 'SSO_SUBJECT' as const : 'STUDENT_NUMBER' as const, value: row.slice(1).join(',').trim() })); try { const updated = await voteApi.importVoterRoll(item.id, { entries: parsed }); setItems((current) => current.map((row) => row.id === updated.id ? updated : row)); } catch { setError('선거인명부를 가져오지 못했습니다.'); } };
  return <section><div className="mb-6 border-b border-kaist-grey/25 pb-4"><h1 className="text-3xl font-extrabold">투표 관리</h1><p className="mt-2 text-sm text-kaist-grey">개설·선거인명부 교체·마감·개표 결과 공개를 관리합니다.</p></div>{error && <p role="alert" className="mb-4 text-red-700">{error}</p>}
    <div className="rounded border bg-white p-5"><h2 className="text-xl font-extrabold">새 투표 개설</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{(['titleKr', 'titleEn', 'descriptionKr', 'descriptionEn', 'candidate1', 'candidate2'] as const).map((key) => <label key={key} className="text-sm font-bold">{key}<input value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="mt-1 block w-full rounded border px-3 py-2 font-normal"/></label>)}<label className="text-sm font-bold">시작<input type="datetime-local" value={form.opensAt} onChange={(event) => setForm((current) => ({ ...current, opensAt: event.target.value }))} className="mt-1 block w-full rounded border px-3 py-2 font-normal"/></label><label className="text-sm font-bold">종료<input type="datetime-local" value={form.closesAt} onChange={(event) => setForm((current) => ({ ...current, closesAt: event.target.value }))} className="mt-1 block w-full rounded border px-3 py-2 font-normal"/></label><label className="text-sm font-bold">유효 투표율(%)<input type="number" min="1" max="100" value={form.validTurnoutPercent} onChange={(event) => setForm((current) => ({ ...current, validTurnoutPercent: event.target.value }))} className="mt-1 block w-full rounded border px-3 py-2 font-normal"/></label></div><button type="button" onClick={() => void create()} disabled={saving} className="mt-5 rounded bg-kaist-darkgreen px-5 py-2 font-bold text-white disabled:opacity-50">{saving ? '저장 중…' : '초안 저장'}</button></div>
    <div className="mt-8 space-y-4">{items.map((item) => <article key={item.id} className="rounded border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">{item.titleKr}</h2><p className="mt-1 text-sm text-kaist-grey">{item.state} · 선거인 {item.eligibleVoterCount}명 · 투표율 {item.turnoutPercent}%</p></div><div className="flex flex-wrap gap-2">{(item.state === 'DRAFT' || item.state === 'SCHEDULED') && <button type="button" onClick={() => void transition(item, 'open')} className="rounded border px-3 py-2 text-sm font-bold">개설</button>}{(item.state === 'OPEN' || item.state === 'SCHEDULED') && <button type="button" onClick={() => void transition(item, 'close')} className="rounded border px-3 py-2 text-sm font-bold">마감</button>}{item.state === 'CLOSED' && <button type="button" onClick={() => void transition(item, 'publish')} className="rounded bg-kaist-darkgreen px-3 py-2 text-sm font-bold text-white">개표·공개</button>}</div></div><label className="mt-4 inline-flex items-center gap-2 text-sm font-bold">선거인명부 CSV/TSV<input type="file" accept=".csv,.tsv,.txt" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importCsv(item, file); event.currentTarget.value = ''; }}/></label><p className="mt-2 text-xs text-kaist-grey">형식: identityKind,value (SSO_SUBJECT 또는 STUDENT_NUMBER). 서버에는 원문 대신 해시만 저장됩니다.</p><ul className="mt-4 grid gap-2 md:grid-cols-2">{item.candidates.map((candidate) => <li key={candidate.id} className="rounded bg-kaist-grey/10 p-3 text-sm font-bold">{candidate.ordinal + 1}. {candidate.nameKr}</li>)}</ul></article>)}</div>
  </section>;
}
