import { useEffect, useState } from 'react';
import type { AdminPledge, PatchPledgeRequest, PledgeStatus } from '@soc/contracts';

import { GovernanceApiError, pledgeApi } from '@/lib/governance-api';

export function AdminPledgesPage() {
  const [items, setItems] = useState<AdminPledge[]>([]);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState<string | null>(null);
  useEffect(() => { void pledgeApi.adminList().then((response) => setItems(response.items)).catch(() => setError('공약 목록을 불러오지 못했습니다.')); }, []);
  const patch = async (item: AdminPledge, input: PatchPledgeRequest) => { setSaving(item.id); setError(''); try { const updated = await pledgeApi.patch(item.id, input); setItems((current) => current.map((row) => row.id === updated.id ? updated : row)); } catch (cause: unknown) { setError(cause instanceof GovernanceApiError ? cause.code ?? '저장에 실패했습니다.' : '저장에 실패했습니다.'); } finally { setSaving(null); } };
  return <section><div className="mb-6 border-b border-kaist-grey/25 pb-4"><h1 className="text-3xl font-extrabold">공약 이행 현황 관리</h1><p className="mt-2 text-sm text-kaist-grey">회장단 권한 보유자만 공약 설명과 진행 상황을 수정할 수 있습니다.</p></div>{error && <p role="alert" className="mb-4 text-red-700">{error}</p>}<div className="space-y-4">{items.map((item) => <article key={item.id} className="rounded border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-extrabold">{item.ordinal + 1}. {item.titleKr}</h2><label className="text-sm font-bold">상태<select value={item.status} onChange={(event) => void patch(item, { status: event.target.value as PledgeStatus })} className="ml-2 rounded border px-2 py-1"><option value="PLANNED">예정</option><option value="IN_PROGRESS">진행 중</option><option value="DONE">완료</option><option value="BLOCKED">보류</option></select></label></div><label className="mt-4 block text-sm font-bold">진척도 {item.progressPercent}%<input type="range" min="0" max="100" value={item.progressPercent} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, progressPercent: Number(event.target.value) } : row))} onMouseUp={(event) => void patch(item, { progressPercent: Number((event.target as HTMLInputElement).value) })} className="mt-2 w-full"/></label><label className="mt-4 block text-sm font-bold">이행 상황<textarea value={item.progressKr} onChange={(event) => setItems((current) => current.map((row) => row.id === item.id ? { ...row, progressKr: event.target.value } : row))} onBlur={(event) => void patch(item, { progressKr: event.target.value })} className="mt-2 min-h-20 w-full rounded border p-3 font-normal"/></label><label className="mt-3 inline-flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={item.isPublished} onChange={(event) => void patch(item, { isPublished: event.target.checked })}/> 공개</label>{saving === item.id && <span className="ml-3 text-xs text-kaist-grey">저장 중…</span>}</article>)}</div></section>;
}
